### ISSUE TITLE
[meta] Objectives

### ISSUE THREAD

**Issue by Lutonite** [heig-lherman/dai-pw04#12]
# Criterion Points

- [x] The README is well structured and explains what the web application is for with its documented application protocol interface (API)
- [x] The README explains the group composition and roles for each member
- [x] The README explains how to install and configure the server with each step
- [x] The README explains how to deploy, run and access the web application
- [x] The README explains how to configure the DNS zone to access your web application
- [x] The README explains how to build and publish the web application with Docker
- [x] The README explains how to interact with the web application with examples and outputs using curl
- [x] The repository is cloned using Git (HTTPS) on the server to run the web application
- [x] Docker and Docker Compose are correctly installed on the server
- [x] The Docker applications (Traefik + API) are split into multiple directories
- [x] The web application runs with Docker and Docker Compose on the server
- [x] You can access the server without a password using a SSH key
- [x] The web application makes usage of at least the following HTTP verbs: GET, POST, PATCH/PUT and DELETE
- [x] The web application can be used using a web browser, a command line tool such as curl or a custom application client
- [x] At least Traefik and your web application are deployed on the server
- [x] The applications are accessible using a domain name and/or subdomain names
- [x] The applications use automatic HTTPS/TLS certificate generations with Let's Encrypt
- [x] The domain names are correctly configured in the DNS zone
- [x] The presentation is clear and well prepared
- [x] Everyone speaks during the presentation, and the presentation lasts the time allowed
- [x] The presentation presents the access to the server and how to clone and run the web application
- [x] The presentation presents the configuration of the DNS zone with its (sub)domain names
- [x] The presentation presents the web application
- [x] A demo of the web application is made using the deployed version of the application (with curl and/or the browser)
- [x] The answers to the questions are correct
